### ISSUE TITLE
wrong Qty on Ender-3 BOM.XLS?

### ISSUE THREAD

**Issue by joewulf** [Creality3DPrinting/Ender-3#11]
400201001 | 42-34 Motor | JK42HS34-0844YA-03F | PCS | 3
400201004 | 42-40 Motor | JK42HS40-1004AC-01F | PCS | 1

should be

400201001 | 42-34 Motor | JK42HS34-0844YA-03F | PCS | 1
400201004 | 42-40 Motor | JK42HS40-1004AC-01F | PCS | 3

**Comment by steenerson** [comment]
Hi @joewulf, only the extruder has a 40mm motor while the XYZ motors are 34mm, the BOM is correct. Closing this out
