### ISSUE TITLE
Error with U8glib on Mac OSx

### ISSUE THREAD

**Issue by RoCoUT** [Creality3DPrinting/Ender-3#17]
So the only error that I am getting is the following:

sorry - this program has been built without plugin support
Using library U8glib at version 1.18 in folder: /Users/xxxxxxxx/Documents/Arduino/libraries/U8glib 
exit status 1
Error compiling for board Sanguino(1284P Boards).

Is their a plugin that will work on Mac and can someone direct me to it?

**Comment by sl1pkn07** [comment]
more log please

**Comment by WesselWessels** [comment]
You need v1.17 of U8glib.

**Comment by steenerson** [comment]
Closing out this old issue, feel free to open a new one if this is ongoing.
