### ISSUE TITLE
Compilation troubles

### ISSUE THREAD

**Issue by F4HFM** [Creality3DPrinting/Ender-3#32]
Hello.
I've some troubles trying t "compile" (Verify) the _Marlin.ino_ project:
using Arduino version 1.8.8
using U8glib 1.19.1
declaring "Sanguino" as board, and "ATmega 1284 or ATmega 1284P (16Mhz)" as processor

When I try a "verif" I have a lot of errors:
- multiple declarations of _FAN_PIN_
- _using typedef-name 'fpos_t' after 'struct'_ error in SdBaseFile.h

Any idea of what I missed?
Thank you!

**Comment by fesiqp** [comment]
@F4HFM I'm submitting PR to fix this right now.

**Comment by fesiqp** [comment]
Fix PR submitted.
PR #33

**Comment by F4HFM** [comment]
Hello fesiqp.
Nice, it seems to be fixed!
Thanks a lot, now I'm waiting for receiving my Ender3 Pro to test it :)
Thanks a lot.

**Comment by tlhintoq** [comment]
Arduino software 1.8.5 or 1.8.9 makes no difference for this.
Trying to compile Marlin 1.1.9 with Ender3 sample conf files (no changes yet, just the out-of-box files for the Ender3.
Compile (verification) fails saying to choose the Sanguino board.  But that's already the board selected.  Version 1.0.2 as specified int he documentation.
Thoughts?
![image](https://user-images.githubusercontent.com/11351506/59966966-91767700-94f1-11e9-9f18-0a92a5522a69.png)

**Comment by ochefe** [comment]
@tlhintoq can you show me which file is in this screenshot? And which version of the repository are you working with?

Also, can you list me which "Processors" are within the "Processor" dropdown, right below the "Board" one you highlighted

**Comment by steenerson** [comment]
I have merged PR 33 and this is complete.

@tlhintoq if you're still seeing an issue let me know and we can reopen this or open a new issue. It's working for me with Arduino 1.8.10 Windows, Sanguino 1.0.3 and U8glib 1.19.1.
