### ISSUE TITLE
git push failed

### ISSUE THREAD

**Issue by schweb5** [Creality3DPrinting/Ender-3#42]
Hi all,
I'd like to contribute to this repo. I have cloned it and done some simple changes to it.
Now when I push it I get the following error message:

`git push
Fatal: AggregateException encountered.
Username for 'https://github.com': 
remote: Permission to Creality3DPrinting/Ender-3.git denied to .
fatal: unable to access 'https://github.com/Creality3DPrinting/Ender-3.git/': The requested URL returned error: 403`

Can anybody help please?
Thanks in advance

**Comment by mavenius** [comment]
It looks like you're trying to push directly to this repo, not your clone of it. What you want to do is push to your clone and then open a pull request into this one. That is a formal request for your changes to be pulled into the repo to which you don't have write permissions. A maintainer of this repo can then review that request and go from there. Hope this helps!

**Comment by steenerson** [comment]
Hi @schweb5, I'm closing this issue since as @mavenius mentioned, the proper method to propose changes to this repo is to submit a pull request.
