### ISSUE TITLE
Files are in Altium format. 

### ISSUE THREAD

**Issue by trininite** [Creality3DPrinting/Ender-3#66]
Hey was wondering how to open or convert the .pcb file you have attached. I have Eagle CAD and Ki Cad

**Comment by VinnyCordeiro** [comment]
> 
> 
> Hey was wondering how to open or convert the .pcb file you have attached. I have Eagle CAD and Ki Cad

There's a project here on Github called altium2kicad that you try: https://github.com/thesourcerer8/altium2kicad It's still very rough, but it works.
