### ISSUE TITLE
Reading PDF Drilling

### ISSUE THREAD

**Issue by davemaster** [Creality3DPrinting/Ender-3#75]
Greetings,

I bought v-slot profiles and I will try to drill the holes for assembly the frame.

![imagen](https://user-images.githubusercontent.com/1075807/142789435-23ef0f1c-5d3b-4188-82bf-47da5a7f9cab.png)

What is the meaning of the picture above: 
1-    4 x 5.2 are 4 holes of 5.2 mm diameter?
2-   9.5 +- (symbol) 5.8 what it means?

Thanks in advance

**Comment by VinnyCordeiro** [comment]
It means that you have 4 through holes of 5.2mm of diameter, and those holes have a counterbore of 9.5mm of diameter that goes 5.8mm deep.

**Comment by davemaster** [comment]
All Clear, thanks a lot
