### ISSUE TITLE
Ender 3 pro extruder plastic support broken - looking to change the extruder?

### ISSUE THREAD

**Issue by andreigabriel4** [Creality3DPrinting/Ender-3#92]
Hello everyone,

I had an issue with my Ender 3 pro printer, nothing came out from the hotend, filament feed wouldn't work. First thing I did was to check the nozzle for clogging but that was not the issue (I also changed the nozzle to a brand new one) and then I tried to manually feed the filament and that worked so I thought that the issue must be from the extruder. 
I checked some youtube videos and came across one named "Ender 3 Filament Feed Issue - Solved" where a guy showed that you should check the U-Shaped Bearing, "just adjust the bearing to align it with the gear". So, naturally, I pulled the plastic support trying to adjust the bearing and broke it so I need to replace either the part or the extruder.

This is a good opportunity to make an upgrade so after making some research I would like some recommendations. What should I choose?
1. Just replace the broken part (probably just the plastic block with an aluminium block)
2. Replacing with a dual drive extruder [the red cheap one]? (I saw some mixed opinions regarding this option)
3. Switch from a bowden tube to a direct drive extruder (solutions like the BMG, swiss, sprite or other extruders)
4. Other solution?

PS. I'm mainly using my Ender 3 printer to make lithophanes and litho' housing. (will upgrade in the future)

Thank you and I appreciate all of your help.

**Comment by andreigabriel4** [comment]
![20230914_171256](https://github.com/Creality3DPrinting/Ender-3/assets/145017681/e5ca4dff-0f3a-4e97-85fd-20084d1f2f0d)

I just added a picture of my extruder so you can see how nicely I broke it.

**Comment by VWguyBruce** [comment]
If you're planning to keep it as your workhorse until you upgrade, keep it stock.

Fastest way to get back up and running.

https://www.amazon.com/Creality-Official-Extruder-3D-Aluminum/dp/B09LQKN5WG/ref=sr_1_1_sspa?keywords=ender%2B3%2Bextruder&link_code=qs&qid=1694704858&sourceid=Mozilla-search&sr=8-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&th=1

**Comment by andreigabriel4** [comment]
> If you're planning to keep it as your workhorse until you upgrade, keep it stock.
> 
> Fastest way to get back up and running.
> 
> https://www.amazon.com/Creality-Official-Extruder-3D-Aluminum/dp/B09LQKN5WG/ref=sr_1_1_sspa?keywords=ender%2B3%2Bextruder&link_code=qs&qid=1694704858&sourceid=Mozilla-search&sr=8-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&th=1

Thank you for recommending @VWguyBruce, I bought the Aluminum extruder, installed it and works perfectly. This should do the job until i upgrade. (I'm currently trying to decide between the Bambu lab P1P or Creality K1 Max)
